version: "3"


services:

  telegram-bot:

    container_name: telegram-bot

    working_dir: /bot_KC

    env_file:
      - .env

    restart: always

    build: .

    command: sh -c "python3 manage.py"