version: "3"


services:

  telegram-bot:

    container_name: telegram-bot

    working_dir: /pythonProject

    restart: always

    build:

        context: .

        dockerfile: Dockerfile
    environment:
      - TELEGRAM_API_TOKEN=5963841255:AAGfwJKvat72Vhq4uVUaZ9jyhsWJyOQ-sLE
    command: sh -c "source /opt/venv/bin/activate && python3 manage.py"